### PR TITLE
Add generate.py to generate enum declarations into tests/py/dcl.enum/

### PR DESCRIPTION
**Pull request by Ukilele**
As we discussed it in [cpplang.slack](https://cpplang.slack.com/archives/C21PKDHSL/p1682283694044249), here is the script to generate C++ declarations. So far it only generates enum declarations. The files will be written to _file-dir_/tests/py/dcl.enum/*.cpp, where _file-dir_ is the directory of the script generate.py. The script uses the python module [exrex](https://github.com/asciimoo/exrex), so please make sure to install it.

Feel free to add a code review or require other changes. In the meantime, I will look into further declarations and how to generate them.

### CODE REVIEW

**Comment by vinniefalco** [comment]
clang does not like those lambda expressions one single bit :)

We need to fix these https://gist.github.com/vinniefalco/af93abfbc947dfb0ecacc2b530befaf4

**Comment by Ukilele** [comment]
Whaaaat? But they are so common in C++...
Joke aside, I will remove them. But just to be clear, clang >= 5.0.0 supports them, if you add "-std=c++2a" (or "-std=c++20" if using a more recent version of clang). If you let me know which compilers/C++ standards we are aiming at, I can take that into account and try to avoid producing invalid or too recent declarations.

**Comment by vinniefalco** [comment]
oh hmm.... well maybe my tests are broken! I am not setting the C++ standard version... I guess that would happen here? https://github.com/cppalliance/mrdox/blob/433c78d52000cdeb4c0dd730985e8de6a57096f0/source/tests/SingleFile.hpp#L35 You have to add those args somehow.

I am targeting the very latest C++ by the way (C++20 I guess, or even C++23 if that's possible).

**Comment by vinniefalco** [comment]
The develop branch uses C++20 for tests now

**Pull request closed without merging**
